server:
  port: 8882
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: kafkaDemo
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
---
spring:
  profiles: dev
  application:
    name: kafkaDemo
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        user-in:
          destination: kafkaDemo
          contentType: application/json
        user-out:
          destination: kafkaDemo
          contentType: application/json
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/world?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: sheng1988
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 30